name: Rust

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-unknown-linux-musl
        override: true
    - uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --release --target x86_64-unknown-linux-musl
    - uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.API_TOKEN }}
      with:
        args: target/x86_64-unknown-linux-musl/release/hd
